# Site settings
title: Cornell Aikido Club
email: octref@gmail.com
description: "Cornell University Aikido Club Website"
baseurl: "/CornellAikido"
url: "https://octref.github.io"

# Build settings
markdown: kramdown
permalink: pretty
