# Site settings
title: Cornell Aikido Club
baseurl: "/CornellAikido"

# Build settings
permalink: pretty

# Default
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "default"

sass:
  sass_dir: "_scss"
